name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
    - uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk11'
        architecture: 'x64'
    - run: sbt test
